### PR TITLE
Introduce npDatabase.json & reduce the amount of human-edited metadata

### PR DESCRIPTION
**Pull request by 20kdc**
EDIT: Status: Should be ready to launch.

### CODE REVIEW

**Comment by ac2pic** [comment]
This should be fun,

**Comment by 20kdc** [comment]
Apparently modifying mod package.json files to correct their incorrect metadata is bad. As such, expect a lot of commits I'm going to have to squish later. For now, do not merge until we've agreed on stuff and I've squished it.

**Comment by 20kdc** [comment]
Regarding linting...
```
/home/travis/build/CCDirectLink/CCModDB/scripts/build.js
  8:7  error  Parsing error: Unexpected token function
```
Um.

**Comment by L-Sherry** [comment]
Can't write on discord, so i'll ask here:

What's the point of providing sha-256 sums if they do not come from the mod author ? Doesn't that break the chain of trust ? From what i understand, this only downloads the zip, assumes that it is trustworthy and hashes it.

**Comment by 20kdc** [comment]
Honestly, I have no idea why the SHA-256 sums exist.

**Comment by L-Sherry** [comment]
I previously assumed that stuff did go as follow:
- author creates zip file of mod and hashes it
- author transmits url and hash using whatever secure channel to moddb maintainers
- maintainer downloads mod
- maintainer checks the hash, to ensure that the download matches the author expectation
- maintainer checks that the mod isn't trying to kill you or ransom your files for *coins
- maintainer publish url and hash

from now on, users could download the mod from a location controlled (or not) by the mod author and check the hash from moddb. If they trust moddb maintainers and the hash is ok, they can assume that what they downloaded was checked by moddb maintainers and, by chain of trust, matches the expectation of the mod author.

**Comment by 20kdc** [comment]
The mod authors publish their mod on some trusted (or 'trusted') service anyway, and if it's GitHub, it's the same service the hashes are held on, so the point's moot.

As such, if the hashes are for security, they'd have to be to make sure that an adversary who has write access to the mod, but not CCModDB (to change the hashes), can't slip anything nasty through.
...Honestly... This probably means the mod author.

**Comment by L-Sherry** [comment]
Git allows you to replace tags with commit that don't even have to be in a branch. That mean Github archives based on tags can be changed by someone with write access to the mod (and that would probably be quite stealthy)... but archives based on commit hash can't be changed, so requiring that is a possibility. That would only require trusting github and ccmoddb (and https).

**Comment by 20kdc** [comment]
Yup. The key thing to note here is that the database rebuilds are supposed to be run, according to the procedure, on a PR. And if doing that is changing the archive hash of a mod it's not supposed to, that means that other archive hash probably has something going on with it...

**Comment by 20kdc** [comment]
The specifications are now actually definitely finalized, with some more leeway given on things that... arguably leeway shouldn't be given on, but regardless.

**Comment by 20kdc** [comment]
Given the rather ridiculous history of this PR, I'm going to squish. Any objections?

**Comment by ac2pic** [comment]
No.

**Comment by 20kdc** [comment]
Well, to solve all of the warnings, there's just kitplayer left.

**Comment by 20kdc** [comment]
@2767mr Basically, is there anything blocking this?

**Comment by 20kdc** [comment]
@ac2pic Given no response from 2767mr, I'm asking you: Is there anything blocking this?

**Pull request merged**
