### PR TITLE
Standardize and require ccmod.json

### PR DESCRIPTION
**Pull request by krypciak**
wasnt so hard huh

### CODE REVIEW

**Comment by L-Sherry** [comment]
This seems to remove the license field, this is not desirable.

**Comment by krypciak** [comment]
We had a discussion about this in the crosscode modding server, and we settled on this.
If you want to discuss it further, I suggest posting in #chat.

**Comment by krypciak** [comment]
includes the CCLoader update in #196

**Comment by krypciak** [comment]
the ci on pr's is a bitch trust me it passed

**Pull request closed without merging**
