### PR TITLE
Bump localize-me to 0.5.3

### PR DESCRIPTION
**Pull request by L-Sherry**
This adds support for localizing DLCs.  And it also fixes bugs.

### CODE REVIEW

**Comment by L-Sherry** [comment]
The build, It is failing. And it's not because of localize-me, because it also fails on master:

https://travis-ci.com/github/CCDirectLink/CCModDB/builds/166573346

**Comment by dmitmel** [comment]
Try rerunning `npm run build`. It should regenerate checksums of the offending packages.

**Comment by L-Sherry** [comment]
I'll prefer not to do that until someone compares the old files and the new ones.

Especially since readable-saves is an uploaded file and not a generated archive, so there is no reason for it to change, unless you did something.

**Comment by dmitmel** [comment]
I changed something in readable-saves (forgot what) without updating the version, sorry about that. Let me see the differences in character swap.

**Comment by dmitmel** [comment]
Interesting. The build on master on my machine fails with the following error:

```
error:  Error: end of central directory record signature not found
    at /home/dmitmel/.local/share/Steam/steamapps/common/CrossCode/CCModDB/build/node_modules/yauzl/index.js:187:14
    at /home/dmitmel/.local/share/Steam/steamapps/common/CrossCode/CCModDB/build/node_modules/yauzl/index.js:631:5
    at Immediate.<anonymous> (/home/dmitmel/.local/share/Steam/steamapps/common/CrossCode/CCModDB/build/node_modules/fd-slicer/index.js:202:5)
    at processImmediate (internal/timers.js:456:21)
```

Fortunately I had the version of CharSwap with the old hash (mentioned in the logs), so I backed it up. cc @2767mr I guess. Can you please add logging?

**Comment by L-Sherry** [comment]
So ? What does diffoscope says ?

**Comment by dmitmel** [comment]
I can't get CCModDB's script to download something and my cached archive is exactly identical to the one at CharSwap's download URL. Commits there are from 2019. Frankly, I have no idea about what had happened to it.

**Pull request merged**
